chore: existing scripts updated.

diff --git a/aayush-ready b/aayush-ready
--- a/aayush-ready
+++ b/aayush-ready
@@ -1,6 +1,14 @@
-#!/bin/bash
+if [ "$#" -gt 1 ]; then
+    echo "Just two arguments are allowed."
+    exit 1
+fi
 
-ssh-add -D 
-
-ssh-add ~/.ssh/personal
-
+if [ "$1" = "0" ]; then
+    ssh-add -D
+    ssh-add ~/.ssh/personal
+elif [ "$1" = "1" ]; then
+    ssh-add -D
+    ssh-add ~/.ssh/ecobeesAayush
+else
+    echo 'Could not ready the user.'
+fi
diff --git a/anugraha-ready b/anugraha-ready
--- a/anugraha-ready
+++ b/anugraha-ready
@@ -1,6 +1,16 @@
 #!/bin/bash
 
-ssh-add -D 
+if [ "$#" -gt 1 ]; then
+    echo "Just two arguments are allowed."
+    exit 1
+fi
 
-ssh-add ~/.ssh/anugraha
-
+if [ "$1" = "0" ]; then
+    ssh-add -D
+    ssh-add ~/.ssh/anugraha
+elif [ "$1" = "1" ]; then
+    ssh-add -D
+    ssh-add ~/.ssh/resAnugraha
+else
+    echo 'Could not ready the user.'
+fi
